import jsPDF from 'jspdf';

export const exportResultsPDF = (result, skills) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246);
  doc.text('AI Interview Results', margin, y);
  y += 15;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
  y += 20;

  doc.setFontSize(40);
  doc.setTextColor(16, 185, 129);
  doc.text(`${result?.overallScore || 0}`, margin, y);
  doc.setFontSize(14);
  doc.text('/100', margin + 35, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(result?.percentile || '', margin, y);
  y += 15;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text('Key Strengths', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  (result?.strengths || []).forEach(s => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(`• ${s.category}: ${s.detail}`, margin + 5, y);
    y += 7;
  });
  y += 5;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text('Areas for Improvement', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  (result?.improvements || []).forEach(s => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(`• ${s.category}: ${s.detail}`, margin + 5, y);
    y += 7;
  });
  y += 5;

  if (skills && skills.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text('Skill Analysis', margin, y);
    y += 8;
    doc.setFontSize(10);
    skills.forEach(s => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setTextColor(60, 60, 60);
      doc.text(`${s.subject}: ${s.candidateScore || s.A || 0}/${s.fullMark || 150}`, margin + 5, y);
      y += 7;
    });
  }

  y += 10;
  if (result?.evaluationTransparency) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text('Evaluation Details', margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const et = result.evaluationTransparency;
    doc.text(`Words Analyzed: ${et.wordsAnalyzed || 0}`, margin + 5, y); y += 7;
    doc.text(`Facial Expressions: ${et.facialExpressions || 0}`, margin + 5, y); y += 7;
    doc.text(`Keyword Clusters: ${et.keywordClusters || 0}`, margin + 5, y); y += 7;
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by AI Interview Platform', margin, 285);

  doc.save(`interview-results-${Date.now()}.pdf`);
};
